### PR TITLE
Don't use deprecated `Repository`

### PR DESCRIPTION
**Pull request by Wauplin**
`Repository` is a deprecated feature in `huggingface_hub`. It is more robust to use the HTTP-based methods from `HfApi` instead. [Here is a doc page explaining why it's better](https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http). Main reasons are 1. don't need to clone a repo to push files 2. faster upload speed 3. don't need git/git+lfs configured locally.

`transformers` switched to use `HfApi` is all their training scripts in Aug 23' (see https://github.com/huggingface/transformers/pull/25095) without breaking. Let's do the same for `parler-tts`!

**Disclaimer:** I did not test those changes myself. Should be fine though.

(Sorry for the import sorting changes. Hope that's fine with you, otherwise I can revert. It is a `ruff format .` side-effect)

Similar PRs: https://github.com/huggingface/peft/pull/1641 https://github.com/huggingface/accelerate/pull/2658

### CODE REVIEW

**Review by sanchit-gandhi — APPROVED** [review]
Thanks for the PR @Wauplin - LGTM. Did we run the linter before pushing this script @ylacombe? We can always run `make style` after merging to keep the consistency with the rest of the repo, but it looks like the `ruff` changes have sorted out the import order properly

**Comment by ylacombe** [comment]
Hey @Wauplin, thanks for the PR, I'll check that it works before merging this!

I actually didn't run linter on the newest version, I'll make sure to do it once after merging this PR

**Comment by Wauplin** [comment]
Thanks for the review and thanks for testing @ylacombe!
Feel free to merge whenever you want/it's ready :)

**Comment by ylacombe** [comment]
Many thanks for the PR @Wauplin! I've superseded the PR because we had some import issues!

**Pull request merged**
