### PR TITLE
Architecture improvements

### PR DESCRIPTION
**Pull request by ylacombe**
Supersedes #50 and #55:
- Add Grouped-Query Attention
- Clean attention
- Add and fix FA2 and SDPA from #55 
- Add prompts in cross attention + RoPE from #50
- Fix generation from #50
- Make RoPE 25% faster
- Add training flexibility in using attention implementaton
- Makes smoother multi-nodes training
- Fix some torch compile and padding issues

### CODE REVIEW

**Comment by Artyom17** [comment]
Any ETA on this to be completed (at least partially) and committed?

**Comment by sanchit-gandhi** [comment]
Should we merge this one when ready @ylacombe to make development of new features more straightforward? After merging this PR, we can open follow-ups to iterate on the design further. Should help with the integration of static cache (#89) among others! cc @eustlb

**Comment by sang-nguyen-ts** [comment]
@ylacombe is there any update on this?

**Comment by ylacombe** [comment]
@sang-nguyen-ts it's just been merged !

**Pull request merged**
