### PR TITLE
Add Flash Attention 2 support to ParlerTTS

### PR DESCRIPTION
**Pull request by sang-nguyen-ts**
# What does this PR do?

According to https://github.com/huggingface/parler-tts/issues/55

The implement mostly based on [MusicGen Flash Ateention PR](https://github.com/huggingface/transformers/pull/29939)

But performance (latency, token/s) of Flash Attention and Eager Attention not so difference!

cc @ylacombe , could you please take a look?

### CODE REVIEW

**Comment by ylacombe** [comment]
Hey @sang-nguyen-ts, thanks so much for opening this issue!
Before giving it a proper review, I already took a look at the benchmark scripts you're using, and I believe you can improve them a bit. Here's an example on how to properly measure latency on a GPU: https://gist.github.com/ylacombe/97890e227600ac165f4117cb69e10b99#file-mha_vs_gqa_llama-py-L23-L54

It uses `torch.cuda.Event` under the hood!

Would you mind re-running the benchmark with that fix and sharing the results here?

> BTW I'm trying implement Static Cache to ParlerTTS for faster inference, and there will be a PR for this later.

Looking forward to this! Feel free to open a PR for Musicgen in `transformers` as well! Static Cache would allow the compilation of the `generate` method, which should give a "free" 20 to 30% speed-up!

> One more question is when will we have v1 version of ParlerTTS?

Soon I hope!

**Comment by sang-nguyen-ts** [comment]
Hi @ylacombe, I've update benchmark code based on the code you provided, here is the result for 50 samples and 86 steps (1s audio):

**Eager Mode:**
```
Execution time: 1.59327421875 seconds
Max memory footprint 4.410230272000001  GB
```

**Flash Attention 2 Mode:**

```
Execution time: 1.4712632812500002 seconds
Max memory footprint 4.4106506240000005  GB
```
**SDPA Mode**

```
Execution time: 1.3303521875000002 seconds
Max memory footprint 4.411184128  GB
```

**Comment by Artyom17** [comment]
Any progress on this? And on static cache implementation?

**Comment by ylacombe** [comment]
Hey @sang-nguyen-ts, 
I've added SDPA and FA2 support in #65, #65 was based on your PR and you're a co-author, many thanks for the effort!

**Pull request closed without merging**
